# Generated by Django 4.2.13 on 2024-07-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='catagory',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
